In [1]:
from facebook_business.api import FacebookAdsApi
from facebook_business.adobjects.adaccount import AdAccount
import pandas as pd
import datetime
from tqdm import tqdm

In [2]:
#탐색 시작, 종료 날짜 정의
start_date = '2022-04-17'
end_date = '2022-04-19'

In [3]:
#광고성과 확인할 브랜드

brands = ['act_354220595454623','act_535583100801605','act_3450253435099519','act_470478278000358']

In [4]:
#시간대별 페이스북 광고 성과확인하는 코드

app_id = '709879300036493'
app_secret = '86af1b41a58488a92092c8e916f85637'
access_token = 'EAAKFoaeDF40BAMZBxuCWPvZBD8nmyTEIBQoZC8ogyIwGziSbXJ2qzK1TPycsC3MnGXX3ikgEl2uNwuxyyhYX0PNsDSCQ7dcJbzXZClKUqKiB8uZBvqHtg76Ly8DUFUZAXOGaM9C9y02NrfDVnpV0x6IGhtZCoW0NclGJzYwMI6ZAPwHlOmVVwQb7'
FacebookAdsApi.init(app_id, app_secret, access_token)

params = {'time_range': {'since': start_date, 'until': end_date},
          'time_increment':1,
          'level': 'adset',
          'sort': ['spend_descending'],
          'export_format':'csv',
          'breakdowns':'hourly_stats_aggregated_by_advertiser_time_zone'
          }
fields = ['account_name',
          'campaign_name',
          'campaign_id',
          'adset_name',
          'adset_id',
          'impressions',
          'clicks',
          'cpm',
          'spend',
          'ctr',
          ]

['account_name',
 'campaign_name',
 'campaign_id',
 'adset_name',
 'adset_id',
 'impressions',
 'clicks',
 'cpm',
 'spend',
 'ctr']

In [6]:
#브랜드별 성과 호출 및 병함
df_list = []


for brand in tqdm(brands):
    insights = list(AdAccount(brand).get_insights(params=params, fields=fields))
    df=pd.DataFrame(columns=fields)
    for field in tqdm(fields):
        df["{}".format(field)]=[x['{}'.format(field)] for x in insights]
    df_list.append(df)

result = pd.concat(df_list)
result

100%|██████████| 10/10 [00:00<00:00, 1258.49it/s]
 25%|██▌       | 1/4 [00:05<00:15,  5.10s/it]C:\Users\yeana shin\AppData\Local\Programs\Python\Python310\lib\site-packages\facebook_business\utils\api_utils.py:30: UserWarning: value of breakdowns might not be compatible.  Expect list<breakdowns_enum>;  got <class 'str'>
  warnings.warn(message)
100%|██████████| 10/10 [00:00<?, ?it/s]
 50%|█████     | 2/4 [00:12<00:12,  6.43s/it]C:\Users\yeana shin\AppData\Local\Programs\Python\Python310\lib\site-packages\facebook_business\utils\api_utils.py:30: UserWarning: value of breakdowns might not be compatible.  Expect list<breakdowns_enum>;  got <class 'str'>
  warnings.warn(message)
100%|██████████| 10/10 [00:00<?, ?it/s]
 75%|███████▌  | 3/4 [00:16<00:05,  5.23s/it]C:\Users\yeana shin\AppData\Local\Programs\Python\Python310\lib\site-packages\facebook_business\utils\api_utils.py:30: UserWarning: value of breakdowns might not be compatible.  Expect list<breakdowns_enum>;  got <class 'str'>
  warnings.warn(message)
100%|██████████| 10/10 [00:00<00:00, 1240.40it/s]
100%|██████████| 4/4 [00:18<00:00,  4.73s/it]

,account_name,campaign_name,campaign_id,adset_name,adset_id,impressions,clicks,cpm,spend,ctr
0,Alloso,220416_사전&얼리버드(자사몰),23850014600830691,인스타그램_Seg1_사전(세그1+2),23850014600840691,740,28,17694.594595,13094,3.783784
1,Alloso,220416_기획전(스마트스토어),23850014539930691,인스타그램_Seg1_기획전,23850034793960691,540,13,22724.074074,12271,2.407407
2,Alloso,220416_사전&얼리버드(자사몰),23850014600830691,인스타그램_Seg1_사전(세그1+2),23850014600840691,801,26,14385.76779,11523,3.245943
3,Alloso,220416_기획전(스마트스토어),23850014539930691,인스타그램_Seg1_기획전,23850034793960691,514,16,22147.859922,11384,3.11284
4,Alloso,220416_기획전(스마트스토어),23850014539930691,인스타그램_Seg2_기획전,23850034829150691,589,14,19288.624788,11361,2.37691
...,...,...,...,...,...,...,...,...,...,...
112,Slou 디큐레이션,220418_상시운영(스마트스토어),23849877135010473,인스타그램_Seg2(토퍼),23849877134990473,53,0,0,0,0
113,Slou 디큐레이션,220418_상시운영(스마트스토어),23849877135010473,인스타그램_Seg2(토퍼),23849877134990473,1,0,0,0,0
114,Slou 디큐레이션,220418_상시운영(스마트스토어),23849877135010473,인스타그램_Seg2(토퍼),23849877134990473,8,0,0,0,0
115,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,52,0,0,0,0
116,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,106,0,0,0,0

In [154]:
result = result.reset_index()

In [13]:
result.to_csv('./temp_result2.csv', encoding = 'utf-8-sig', index = False)

In [133]:
#알로소 성과 호출
insights = list(AdAccount('act_354220595454623').get_insights(params=params, fields=fields))
insights

C:\Users\DQ_dcuration\anaconda3\lib\site-packages\facebook_business\utils\api_utils.py:30: UserWarning: value of breakdowns might not be compatible.  Expect list<breakdowns_enum>;  got <class 'str'>
  warnings.warn(message)

[<AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "28",
     "cpm": "17694.594595",
     "ctr": "3.783784",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "740",
     "spend": "13094"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "26",
     "cpm": "14385.76779",
     "ctr": "3.245943",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "801",
     "spend": "11523"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "20",
     "cpm": "15275.18797",
     "ctr": "3.007519",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "665",
     "spend": "10158"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "14",
     "cpm": "18313.320826",
     "ctr": "2.626642",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "17:00:00 - 17:59:59",
     "impressions": "533",
     "spend": "9761"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "23",
     "cpm": "16503.389831",
     "ctr": "3.898305",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "08:00:00 - 08:59:59",
     "impressions": "590",
     "spend": "9737"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "17",
     "cpm": "16030.405405",
     "ctr": "2.871622",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "18:00:00 - 18:59:59",
     "impressions": "592",
     "spend": "9490"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "20",
     "cpm": "16494.699647",
     "ctr": "3.533569",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "566",
     "spend": "9336"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "10",
     "cpm": "16207.446809",
     "ctr": "1.77305",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "09:00:00 - 09:59:59",
     "impressions": "564",
     "spend": "9141"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "15",
     "cpm": "16619.230769",
     "ctr": "2.884615",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "16:00:00 - 16:59:59",
     "impressions": "520",
     "spend": "8642"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "16",
     "cpm": "17951.167728",
     "ctr": "3.397028",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "10:00:00 - 10:59:59",
     "impressions": "471",
     "spend": "8455"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "14",
     "cpm": "20446.153846",
     "ctr": "3.589744",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "14:00:00 - 14:59:59",
     "impressions": "390",
     "spend": "7974"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "14",
     "cpm": "18304.849885",
     "ctr": "3.233256",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "13:00:00 - 13:59:59",
     "impressions": "433",
     "spend": "7926"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "15",
     "cpm": "20048.648649",
     "ctr": "4.054054",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "12:00:00 - 12:59:59",
     "impressions": "370",
     "spend": "7418"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "16",
     "cpm": "15065.12605",
     "ctr": "3.361345",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "07:00:00 - 07:59:59",
     "impressions": "476",
     "spend": "7171"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "13",
     "cpm": "18639.257294",
     "ctr": "3.448276",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "11:00:00 - 11:59:59",
     "impressions": "377",
     "spend": "7027"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "17",
     "cpm": "16878.934625",
     "ctr": "4.116223",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "15:00:00 - 15:59:59",
     "impressions": "413",
     "spend": "6971"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "10",
     "cpm": "12233.26572",
     "ctr": "2.028398",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "493",
     "spend": "6031"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "8",
     "cpm": "18591.240876",
     "ctr": "2.919708",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "01:00:00 - 01:59:59",
     "impressions": "274",
     "spend": "5094"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "9",
     "cpm": "19900",
     "ctr": "4.090909",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "00:00:00 - 00:59:59",
     "impressions": "220",
     "spend": "4378"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034793960691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "11",
     "cpm": "15889.328063",
     "ctr": "4.347826",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "253",
     "spend": "4020"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034829150691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "14",
     "cpm": "13031.034483",
     "ctr": "4.827586",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "290",
     "spend": "3779"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034793960691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "11",
     "cpm": "21692.307692",
     "ctr": "6.508876",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "169",
     "spend": "3666"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034829150691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "10",
     "cpm": "17567.164179",
     "ctr": "4.975124",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "201",
     "spend": "3531"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034829150691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "10",
     "cpm": "17383.783784",
     "ctr": "5.405405",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "185",
     "spend": "3216"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "8",
     "cpm": "15485.294118",
     "ctr": "3.921569",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "06:00:00 - 06:59:59",
     "impressions": "204",
     "spend": "3159"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034829150691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "3",
     "cpm": "17404.624277",
     "ctr": "1.734104",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "173",
     "spend": "3011"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034793960691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "6",
     "cpm": "15977.272727",
     "ctr": "3.409091",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "176",
     "spend": "2812"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034829150691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "4",
     "cpm": "21414.0625",
     "ctr": "3.125",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "18:00:00 - 18:59:59",
     "impressions": "128",
     "spend": "2741"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034793960691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "6",
     "cpm": "21896",
     "ctr": "4.8",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "125",
     "spend": "2737"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850014600840691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc0ac\uc804(\uc138\uadf81+2)",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "5",
     "cpm": "14545.977011",
     "ctr": "2.873563",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "02:00:00 - 02:59:59",
     "impressions": "174",
     "spend": "2531"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034793960691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "3",
     "cpm": "15652.173913",
     "ctr": "1.863354",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "161",
     "spend": "2520"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034793960691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "8",
     "cpm": "19125.984252",
     "ctr": "6.299213",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "18:00:00 - 18:59:59",
     "impressions": "127",
     "spend": "2429"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034793960691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "4",
     "cpm": "19396.694215",
     "ctr": "3.305785",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "14:00:00 - 14:59:59",
     "impressions": "121",
     "spend": "2347"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034960400691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg3_\uc5bc\ub9ac\ubc84\ub4dc",
     "campaign_id": "23850014600830691",
     "campaign_name": "220416_\uc0ac\uc804&\uc5bc\ub9ac\ubc84\ub4dc(\uc790\uc0ac\ubab0)",
     "clicks": "6",
     "cpm": "9112.5",
     "ctr": "2.5",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "240",
     "spend": "2187"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034829150691",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2_\uae30\ud68d\uc804",
     "campaign_id": "23850014539930691",
     "campaign_name": "220416_\uae30\ud68d\uc804(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "7",
     "cpm": "15712.121212",
     "ctr": "5.30303",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "132",
     "spend": "2074"
 },
 <AdsInsights> {
     "account_name": "Alloso",
     "adset_id": "23850034793960691",

In [6]:
#데이터 세분화 단계를 보기 위한 필드 재정의
fields2 = ['account_name',
          'campaign_name',
          'campaign_id',
          'adset_name',
          'adset_id',
          'hourly_stats_aggregated_by_advertiser_time_zone',
          'impressions',
          'clicks',
          'cpm',
          'spend',
          'ctr',
           "date_stop"
          ]

In [147]:
df=pd.DataFrame(columns=fields)
for field in fields2:
    df["{}".format(field)]=[x['{}'.format(field)] for x in insights]

df

,account_name,campaign_name,campaign_id,adset_name,adset_id,impressions,clicks,cpm,spend,ctr,hourly_stats_aggregated_by_advertiser_time_zone,date_stop
0,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,722,22,18139.889197,13097,3.047091,22:00:00 - 22:59:59,2022-04-17
1,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,756,21,17179.89418,12988,2.777778,16:00:00 - 16:59:59,2022-04-17
2,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,667,21,19238.38081,12832,3.148426,21:00:00 - 21:59:59,2022-04-17
3,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,661,17,17757.942511,11738,2.571861,19:00:00 - 19:59:59,2022-04-17
4,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,683,21,16269.399707,11112,3.074671,15:00:00 - 15:59:59,2022-04-17
5,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,611,10,17369.885434,10613,1.636661,17:00:00 - 17:59:59,2022-04-17
6,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,560,16,18657.142857,10448,2.857143,18:00:00 - 18:59:59,2022-04-17
7,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,544,21,18080.882353,9836,3.860294,20:00:00 - 20:59:59,2022-04-17
8,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,711,16,13320.675105,9471,2.250352,23:00:00 - 23:59:59,2022-04-17
9,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,366,13,15379.781421,5629,3.551913,23:00:00 - 23:59:59,2022-04-17
10,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,188,9,25765.957447,4844,4.787234,10:00:00 - 10:59:59,2022-04-17
11,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,302,10,15791.390728,4769,3.311258,00:00:00 - 00:59:59,2022-04-17
12,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,224,7,19348.214286,4334,3.125,08:00:00 - 08:59:59,2022-04-17
13,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,171,8,22672.51462,3877,4.678363,22:00:00 - 22:59:59,2022-04-17
14,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,190,5,18952.631579,3601,2.631579,21:00:00 - 21:59:59,2022-04-17
15,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,233,0,15266.094421,3557,0,16:00:00 - 16:59:59,2022-04-17
16,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,241,6,14406.639004,3472,2.489627,09:00:00 - 09:59:59,2022-04-17
17,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,114,6,29938.596491,3413,5.263158,02:00:00 - 02:59:59,2022-04-17
18,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,104,4,28865.384615,3002,3.846154,10:00:00 - 10:59:59,2022-04-17
19,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,206,5,13140.776699,2707,2.427184,01:00:00 - 01:59:59,2022-04-17
20,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,85,4,30917.647059,2628,4.705882,00:00:00 - 00:59:59,2022-04-17
21,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,112,3,21491.071429,2407,2.678571,20:00:00 - 20:59:59,2022-04-17
22,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,134,2,17708.955224,2373,1.492537,17:00:00 - 17:59:59,2022-04-17
23,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,65,4,34507.692308,2243,6.153846,05:00:00 - 05:59:59,2022-04-17
24,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,76,3,29157.894737,2216,3.947368,08:00:00 - 08:59:59,2022-04-17
25,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,80,4,25550,2044,5,12:00:00 - 12:59:59,2022-04-17
26,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,65,3,29846.153846,1940,4.615385,12:00:00 - 12:59:59,2022-04-17
27,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,112,4,16535.714286,1852,3.571429,19:00:00 - 19:59:59,2022-04-17
28,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,98,1,17918.367347,1756,1.020408,18:00:00 - 18:59:59,2022-04-17
29,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,178,3,9752.808989,1736,1.685393,07:00:00 - 07:59:59,2022-04-17
30,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,77,3,22194.805195,1709,3.896104,06:00:00 - 06:59:59,2022-04-17
31,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,25,2,60600,1515,8,04:00:00 - 04:59:59,2022-04-17
32,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,18,2,80388.888889,1447,11.111111,05:00:00 - 05:59:59,2022-04-17
33,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,116,2,11818.965517,1371,1.724138,14:00:00 - 14:59:59,2022-04-17
34,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,65,2,20246.153846,1316,3.076923,07:00:00 - 07:59:59,2022-04-17
35,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,95,2,13263.157895,1260,2.105263,11:00:00 - 11:59:59,2022-04-17
36,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,84,2,12857.142857,1080,2.380952,03:00:00 - 03:59:59,2022-04-17
37,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,65,0,12446.153846,809,0,15:00:00 - 15:59:59,2022-04-17
38,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,82,2,9304.878049,763,2.439024,09:00:00 - 09:59:59,2022-04-17
39,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,125,2,6032,754,1.6,11:00:00 - 11:59:59,2022-04-17
40,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,33,1,21787.878788,719,3.030303,03:00:00 - 03:59:59,2022-04-17
41,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,41,1,17390.243902,713,2.439024,06:00:00 - 06:59:59,2022-04-17
42,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,69,1,9463.768116,653,1.449275,04:00:00 - 04:59:59,2022-04-17
43,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,33,2,10151.515152,335,6.060606,14:00:00 - 14:59:59,2022-04-17
44,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,2,0,11000,22,0,13:00:00 - 13:59:59,2022-04-17
45,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,2,0,3000,6,0,13:00:00 - 13:59:59,2022-04-17
46,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,52,0,0,0,0,02:00:00 - 02:59:59,2022-04-17
47,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,106,0,0,0,0,01:00:00 - 01:59:59,2022-04-17

In [116]:
insights2 = list(AdAccount('act_535583100801605').get_insights(params=params, fields=fields))
insights2

C:\Users\DQ_dcuration\anaconda3\lib\site-packages\facebook_business\utils\api_utils.py:30: UserWarning: value of breakdowns might not be compatible.  Expect list<breakdowns_enum>;  got <class 'str'>
  warnings.warn(message)

[<AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851096983340369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg3_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "28",
     "cpm": "11590.973202",
     "ctr": "3.949224",
     "date_start": "2022-04-11",
     "date_stop": "2022-04-11",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "709",
     "spend": "8218"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851096987770369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg3_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "12",
     "cpm": "10460.545194",
     "ctr": "1.721664",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "697",
     "spend": "7291"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851096983340369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg3_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "17",
     "cpm": "10778.443114",
     "ctr": "2.54491",
     "date_start": "2022-04-12",
     "date_stop": "2022-04-12",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "668",
     "spend": "7200"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "14",
     "cpm": "14943.44473",
     "ctr": "3.598972",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "00:00:00 - 00:59:59",
     "impressions": "389",
     "spend": "5813"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "17",
     "cpm": "12912.442396",
     "ctr": "3.917051",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "434",
     "spend": "5604"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "15",
     "cpm": "17805.732484",
     "ctr": "4.77707",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "314",
     "spend": "5591"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "12",
     "cpm": "15363.380282",
     "ctr": "3.380282",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "355",
     "spend": "5454"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "33",
     "cpm": "13857.512953",
     "ctr": "8.549223",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "386",
     "spend": "5349"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851134284620369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\ucea3\ud0c0\uc6cc",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "31",
     "cpm": "15255.014327",
     "ctr": "8.882521",
     "date_start": "2022-04-10",
     "date_stop": "2022-04-10",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "349",
     "spend": "5324"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "22",
     "cpm": "12217.703349",
     "ctr": "5.263158",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "418",
     "spend": "5107"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "17",
     "cpm": "13675.675676",
     "ctr": "4.594595",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "11:00:00 - 11:59:59",
     "impressions": "370",
     "spend": "5060"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "14",
     "cpm": "15415.625",
     "ctr": "4.375",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "15:00:00 - 15:59:59",
     "impressions": "320",
     "spend": "4933"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "13",
     "cpm": "15229.813665",
     "ctr": "4.037267",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "17:00:00 - 17:59:59",
     "impressions": "322",
     "spend": "4904"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "13",
     "cpm": "12970.899471",
     "ctr": "3.439153",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "378",
     "spend": "4903"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "11",
     "cpm": "15069.18239",
     "ctr": "3.45912",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "318",
     "spend": "4792"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "8",
     "cpm": "19794.97908",
     "ctr": "3.34728",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "09:00:00 - 09:59:59",
     "impressions": "239",
     "spend": "4731"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "24",
     "cpm": "14245.454545",
     "ctr": "7.272727",
     "date_start": "2022-04-11",
     "date_stop": "2022-04-11",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "330",
     "spend": "4701"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "13",
     "cpm": "16751.798561",
     "ctr": "4.676259",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "16:00:00 - 16:59:59",
     "impressions": "278",
     "spend": "4657"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "17",
     "cpm": "15339.933993",
     "ctr": "5.610561",
     "date_start": "2022-04-12",
     "date_stop": "2022-04-12",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "303",
     "spend": "4648"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851134284620369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\ucea3\ud0c0\uc6cc",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "13",
     "cpm": "13984.27673",
     "ctr": "4.08805",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "318",
     "spend": "4447"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851134284620369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\ucea3\ud0c0\uc6cc",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "10",
     "cpm": "15607.142857",
     "ctr": "3.571429",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "280",
     "spend": "4370"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "10",
     "cpm": "16853.281853",
     "ctr": "3.861004",
     "date_start": "2022-04-11",
     "date_stop": "2022-04-11",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "259",
     "spend": "4365"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "6",
     "cpm": "18952.173913",
     "ctr": "2.608696",
     "date_start": "2022-04-10",
     "date_stop": "2022-04-10",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "230",
     "spend": "4359"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "8",
     "cpm": "17425.702811",
     "ctr": "3.212851",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "18:00:00 - 18:59:59",
     "impressions": "249",
     "spend": "4339"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "18",
     "cpm": "14388.704319",
     "ctr": "5.980066",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "301",
     "spend": "4331"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "25",
     "cpm": "14058.441558",
     "ctr": "8.116883",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "17:00:00 - 17:59:59",
     "impressions": "308",
     "spend": "4330"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "14",
     "cpm": "16525.096525",
     "ctr": "5.405405",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "14:00:00 - 14:59:59",
     "impressions": "259",
     "spend": "4280"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "13",
     "cpm": "12464.912281",
     "ctr": "3.80117",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "342",
     "spend": "4263"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "9",
     "cpm": "14039.60396",
     "ctr": "2.970297",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "17:00:00 - 17:59:59",
     "impressions": "303",
     "spend": "4254"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851134284620369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\ucea3\ud0c0\uc6cc",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "22",
     "cpm": "13492.063492",
     "ctr": "6.984127",
     "date_start": "2022-04-11",
     "date_stop": "2022-04-11",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "315",
     "spend": "4250"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851134284620369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\ucea3\ud0c0\uc6cc",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "18",
     "cpm": "14418.367347",
     "ctr": "6.122449",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "294",
     "spend": "4239"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "19",
     "cpm": "14310.810811",
     "ctr": "6.418919",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "296",
     "spend": "4236"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851079385950369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uce68\ub300",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "28",
     "cpm": "13963.210702",
     "ctr": "9.364548",
     "date_start": "2022-04-11",
     "date_stop": "2022-04-11",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "299",
     "spend": "4175"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_\uc18c\ud30c",
     "campaign_id": "23851072480170369",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc790\uc0ac\ubab0)",
     "clicks": "12",
     "cpm": "12086.956522",
     "ctr": "3.478261",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "345",
     "spend": "4170"
 },
 <AdsInsights> {
     "account_name": "\uc77c\ub8f8 X \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23851072480200369",

In [118]:
df=pd.DataFrame(columns=fields2)
for field in fields2:
    df["{}".format(field)]=[x['{}'.format(field)] for x in insights2]

df

,account_name,campaign_name,campaign_id,adset_name,adset_id,hourly_stats_aggregated_by_advertiser_time_zone,impressions,clicks,cpm,spend,ctr
0,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg3_침대,23851096983340369,23:00:00 - 23:59:59,709,28,11590.973202,8218,3.949224
1,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg3_소파,23851096987770369,23:00:00 - 23:59:59,697,12,10460.545194,7291,1.721664
2,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg3_침대,23851096983340369,23:00:00 - 23:59:59,668,17,10778.443114,7200,2.54491
3,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg1_소파,23851072480200369,00:00:00 - 00:59:59,389,14,14943.44473,5813,3.598972
4,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg1_침대,23851079385950369,22:00:00 - 22:59:59,434,17,12912.442396,5604,3.917051
...,...,...,...,...,...,...,...,...,...,...,...
955,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg3_소파,23851096987770369,06:00:00 - 06:59:59,5,0,3600,18,0
956,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg3_소파,23851096987770369,05:00:00 - 05:59:59,4,0,4500,18,0
957,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg3_소파,23851096987770369,04:00:00 - 04:59:59,3,0,6000,18,0
958,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg3_소파,23851096987770369,04:00:00 - 04:59:59,1,0,4000,4,0
959,일룸 X 디큐레이션,220401_상시운영(자사몰),23851072480170369,인스타그램_Seg3_소파,23851096987770369,03:00:00 - 03:59:59,2,0,1000,2,0

In [142]:
#슬로우
insights3 = list(AdAccount('act_470478278000358').get_insights(params=params, fields=fields))
insights3

C:\Users\DQ_dcuration\anaconda3\lib\site-packages\facebook_business\utils\api_utils.py:30: UserWarning: value of breakdowns might not be compatible.  Expect list<breakdowns_enum>;  got <class 'str'>
  warnings.warn(message)

[<AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "22",
     "cpm": "18139.889197",
     "ctr": "3.047091",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "722",
     "spend": "13097"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "21",
     "cpm": "17179.89418",
     "ctr": "2.777778",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "16:00:00 - 16:59:59",
     "impressions": "756",
     "spend": "12988"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "21",
     "cpm": "19238.38081",
     "ctr": "3.148426",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "667",
     "spend": "12832"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "17",
     "cpm": "17757.942511",
     "ctr": "2.571861",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "661",
     "spend": "11738"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "21",
     "cpm": "16269.399707",
     "ctr": "3.074671",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "15:00:00 - 15:59:59",
     "impressions": "683",
     "spend": "11112"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "10",
     "cpm": "17369.885434",
     "ctr": "1.636661",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "17:00:00 - 17:59:59",
     "impressions": "611",
     "spend": "10613"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "16",
     "cpm": "18657.142857",
     "ctr": "2.857143",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "18:00:00 - 18:59:59",
     "impressions": "560",
     "spend": "10448"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "21",
     "cpm": "18080.882353",
     "ctr": "3.860294",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "544",
     "spend": "9836"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "16",
     "cpm": "13320.675105",
     "ctr": "2.250352",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "711",
     "spend": "9471"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "13",
     "cpm": "15379.781421",
     "ctr": "3.551913",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "366",
     "spend": "5629"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "9",
     "cpm": "25765.957447",
     "ctr": "4.787234",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "10:00:00 - 10:59:59",
     "impressions": "188",
     "spend": "4844"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "10",
     "cpm": "15791.390728",
     "ctr": "3.311258",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "00:00:00 - 00:59:59",
     "impressions": "302",
     "spend": "4769"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "7",
     "cpm": "19348.214286",
     "ctr": "3.125",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "08:00:00 - 08:59:59",
     "impressions": "224",
     "spend": "4334"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "8",
     "cpm": "22672.51462",
     "ctr": "4.678363",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "171",
     "spend": "3877"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "5",
     "cpm": "18952.631579",
     "ctr": "2.631579",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "190",
     "spend": "3601"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "0",
     "cpm": "15266.094421",
     "ctr": "0",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "16:00:00 - 16:59:59",
     "impressions": "233",
     "spend": "3557"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "6",
     "cpm": "14406.639004",
     "ctr": "2.489627",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "09:00:00 - 09:59:59",
     "impressions": "241",
     "spend": "3472"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "6",
     "cpm": "29938.596491",
     "ctr": "5.263158",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "02:00:00 - 02:59:59",
     "impressions": "114",
     "spend": "3413"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "4",
     "cpm": "28865.384615",
     "ctr": "3.846154",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "10:00:00 - 10:59:59",
     "impressions": "104",
     "spend": "3002"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "5",
     "cpm": "13140.776699",
     "ctr": "2.427184",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "01:00:00 - 01:59:59",
     "impressions": "206",
     "spend": "2707"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "4",
     "cpm": "30917.647059",
     "ctr": "4.705882",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "00:00:00 - 00:59:59",
     "impressions": "85",
     "spend": "2628"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "3",
     "cpm": "21491.071429",
     "ctr": "2.678571",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "112",
     "spend": "2407"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "2",
     "cpm": "17708.955224",
     "ctr": "1.492537",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "17:00:00 - 17:59:59",
     "impressions": "134",
     "spend": "2373"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "4",
     "cpm": "34507.692308",
     "ctr": "6.153846",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "05:00:00 - 05:59:59",
     "impressions": "65",
     "spend": "2243"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "3",
     "cpm": "29157.894737",
     "ctr": "3.947368",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "08:00:00 - 08:59:59",
     "impressions": "76",
     "spend": "2216"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "4",
     "cpm": "25550",
     "ctr": "5",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "12:00:00 - 12:59:59",
     "impressions": "80",
     "spend": "2044"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "3",
     "cpm": "29846.153846",
     "ctr": "4.615385",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "12:00:00 - 12:59:59",
     "impressions": "65",
     "spend": "1940"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "4",
     "cpm": "16535.714286",
     "ctr": "3.571429",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "112",
     "spend": "1852"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "1",
     "cpm": "17918.367347",
     "ctr": "1.020408",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "18:00:00 - 18:59:59",
     "impressions": "98",
     "spend": "1756"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "3",
     "cpm": "9752.808989",
     "ctr": "1.685393",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "07:00:00 - 07:59:59",
     "impressions": "178",
     "spend": "1736"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "3",
     "cpm": "22194.805195",
     "ctr": "3.896104",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "06:00:00 - 06:59:59",
     "impressions": "77",
     "spend": "1709"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "2",
     "cpm": "60600",
     "ctr": "8",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "04:00:00 - 04:59:59",
     "impressions": "25",
     "spend": "1515"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1(\ub9e4\ud2b8\ub9ac\uc2a4)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "2",
     "cpm": "80388.888889",
     "ctr": "11.111111",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "05:00:00 - 05:59:59",
     "impressions": "18",
     "spend": "1447"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838746740473",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg2(\ud1a0\ud37c)",
     "campaign_id": "23849838734570473",
     "campaign_name": "220411_\uc0c1\uc2dc\uc6b4\uc601(\uc624\ub298\uc758\uc9d1)",
     "clicks": "2",
     "cpm": "11818.965517",
     "ctr": "1.724138",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "14:00:00 - 14:59:59",
     "impressions": "116",
     "spend": "1371"
 },
 <AdsInsights> {
     "account_name": "Slou \ub514\ud050\ub808\uc774\uc158",
     "adset_id": "23849838734550473",

In [143]:
df=pd.DataFrame(columns=fields2)
for field in fields2:
    df["{}".format(field)]=[x['{}'.format(field)] for x in insights3]

df

,account_name,campaign_name,campaign_id,adset_name,adset_id,hourly_stats_aggregated_by_advertiser_time_zone,impressions,clicks,cpm,spend,ctr
0,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,22:00:00 - 22:59:59,722,22,18139.889197,13097,3.047091
1,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,16:00:00 - 16:59:59,756,21,17179.89418,12988,2.777778
2,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,21:00:00 - 21:59:59,667,21,19238.38081,12832,3.148426
3,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,19:00:00 - 19:59:59,661,17,17757.942511,11738,2.571861
4,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,15:00:00 - 15:59:59,683,21,16269.399707,11112,3.074671
5,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,17:00:00 - 17:59:59,611,10,17369.885434,10613,1.636661
6,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,18:00:00 - 18:59:59,560,16,18657.142857,10448,2.857143
7,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,20:00:00 - 20:59:59,544,21,18080.882353,9836,3.860294
8,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,23:00:00 - 23:59:59,711,16,13320.675105,9471,2.250352
9,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,23:00:00 - 23:59:59,366,13,15379.781421,5629,3.551913
10,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,10:00:00 - 10:59:59,188,9,25765.957447,4844,4.787234
11,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,00:00:00 - 00:59:59,302,10,15791.390728,4769,3.311258
12,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,08:00:00 - 08:59:59,224,7,19348.214286,4334,3.125
13,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,22:00:00 - 22:59:59,171,8,22672.51462,3877,4.678363
14,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,21:00:00 - 21:59:59,190,5,18952.631579,3601,2.631579
15,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,16:00:00 - 16:59:59,233,0,15266.094421,3557,0
16,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,09:00:00 - 09:59:59,241,6,14406.639004,3472,2.489627
17,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,02:00:00 - 02:59:59,114,6,29938.596491,3413,5.263158
18,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,10:00:00 - 10:59:59,104,4,28865.384615,3002,3.846154
19,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,01:00:00 - 01:59:59,206,5,13140.776699,2707,2.427184
20,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,00:00:00 - 00:59:59,85,4,30917.647059,2628,4.705882
21,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,20:00:00 - 20:59:59,112,3,21491.071429,2407,2.678571
22,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,17:00:00 - 17:59:59,134,2,17708.955224,2373,1.492537
23,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,05:00:00 - 05:59:59,65,4,34507.692308,2243,6.153846
24,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,08:00:00 - 08:59:59,76,3,29157.894737,2216,3.947368
25,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,12:00:00 - 12:59:59,80,4,25550,2044,5
26,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,12:00:00 - 12:59:59,65,3,29846.153846,1940,4.615385
27,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,19:00:00 - 19:59:59,112,4,16535.714286,1852,3.571429
28,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,18:00:00 - 18:59:59,98,1,17918.367347,1756,1.020408
29,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,07:00:00 - 07:59:59,178,3,9752.808989,1736,1.685393
30,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,06:00:00 - 06:59:59,77,3,22194.805195,1709,3.896104
31,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,04:00:00 - 04:59:59,25,2,60600,1515,8
32,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,05:00:00 - 05:59:59,18,2,80388.888889,1447,11.111111
33,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,14:00:00 - 14:59:59,116,2,11818.965517,1371,1.724138
34,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,07:00:00 - 07:59:59,65,2,20246.153846,1316,3.076923
35,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,11:00:00 - 11:59:59,95,2,13263.157895,1260,2.105263
36,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,03:00:00 - 03:59:59,84,2,12857.142857,1080,2.380952
37,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,15:00:00 - 15:59:59,65,0,12446.153846,809,0
38,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,09:00:00 - 09:59:59,82,2,9304.878049,763,2.439024
39,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,11:00:00 - 11:59:59,125,2,6032,754,1.6
40,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,03:00:00 - 03:59:59,33,1,21787.878788,719,3.030303
41,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,06:00:00 - 06:59:59,41,1,17390.243902,713,2.439024
42,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,04:00:00 - 04:59:59,69,1,9463.768116,653,1.449275
43,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,14:00:00 - 14:59:59,33,2,10151.515152,335,6.060606
44,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,13:00:00 - 13:59:59,2,0,11000,22,0
45,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg2(토퍼),23849838746740473,13:00:00 - 13:59:59,2,0,3000,6,0
46,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,02:00:00 - 02:59:59,52,0,0,0,0
47,Slou 디큐레이션,220411_상시운영(오늘의집),23849838734570473,인스타그램_Seg1(매트리스),23849838734550473,01:00:00 - 01:59:59,106,0,0,0,0

In [121]:
#데스커
insights4 = list(AdAccount('act_3450253435099519').get_insights(params=params, fields=fields))
insights4

C:\Users\DQ_dcuration\anaconda3\lib\site-packages\facebook_business\utils\api_utils.py:30: UserWarning: value of breakdowns might not be compatible.  Expect list<breakdowns_enum>;  got <class 'str'>
  warnings.warn(message)

[<AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "47",
     "cpm": "19270.870871",
     "ctr": "2.822823",
     "date_start": "2022-04-16",
     "date_stop": "2022-04-16",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "1665",
     "spend": "32086"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "53",
     "cpm": "20546.056991",
     "ctr": "3.51226",
     "date_start": "2022-04-12",
     "date_stop": "2022-04-12",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "1509",
     "spend": "31004"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "40",
     "cpm": "20492.173913",
     "ctr": "3.478261",
     "date_start": "2022-04-12",
     "date_stop": "2022-04-12",
     "hourly_stats_aggregated_by_advertiser_time_zone": "18:00:00 - 18:59:59",
     "impressions": "1150",
     "spend": "23566"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "38",
     "cpm": "21740.465116",
     "ctr": "3.534884",
     "date_start": "2022-04-12",
     "date_stop": "2022-04-12",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "1075",
     "spend": "23371"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "38",
     "cpm": "25973.9819",
     "ctr": "4.298643",
     "date_start": "2022-04-12",
     "date_stop": "2022-04-12",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "884",
     "spend": "22961"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "34",
     "cpm": "26498.837209",
     "ctr": "3.953488",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "21:00:00 - 21:59:59",
     "impressions": "860",
     "spend": "22789"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "37",
     "cpm": "28853.856563",
     "ctr": "5.006766",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "14:00:00 - 14:59:59",
     "impressions": "739",
     "spend": "21323"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "29",
     "cpm": "13721.107266",
     "ctr": "2.00692",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "1445",
     "spend": "19827"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "33",
     "cpm": "21481.561822",
     "ctr": "3.579176",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "09:00:00 - 09:59:59",
     "impressions": "922",
     "spend": "19806"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "29",
     "cpm": "16939.212329",
     "ctr": "2.482877",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "1168",
     "spend": "19785"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "31",
     "cpm": "22368.965517",
     "ctr": "3.563218",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "16:00:00 - 16:59:59",
     "impressions": "870",
     "spend": "19461"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "26",
     "cpm": "19951.467269",
     "ctr": "2.934537",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "886",
     "spend": "17677"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "25",
     "cpm": "18687.912088",
     "ctr": "2.747253",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "18:00:00 - 18:59:59",
     "impressions": "910",
     "spend": "17006"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "25",
     "cpm": "27387.987013",
     "ctr": "4.058442",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "12:00:00 - 12:59:59",
     "impressions": "616",
     "spend": "16871"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "27",
     "cpm": "21750.977836",
     "ctr": "3.520209",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "14:00:00 - 14:59:59",
     "impressions": "767",
     "spend": "16683"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "29",
     "cpm": "21230.179028",
     "ctr": "3.70844",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "13:00:00 - 13:59:59",
     "impressions": "782",
     "spend": "16602"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "29",
     "cpm": "25609.567901",
     "ctr": "4.475309",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "15:00:00 - 15:59:59",
     "impressions": "648",
     "spend": "16595"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "26",
     "cpm": "19919.805589",
     "ctr": "3.159174",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "823",
     "spend": "16394"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "25",
     "cpm": "14468.468468",
     "ctr": "2.252252",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "1110",
     "spend": "16060"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "31",
     "cpm": "15757.242757",
     "ctr": "3.096903",
     "date_start": "2022-04-12",
     "date_stop": "2022-04-12",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "1001",
     "spend": "15773"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "26",
     "cpm": "14606.511628",
     "ctr": "2.418605",
     "date_start": "2022-04-12",
     "date_stop": "2022-04-12",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "1075",
     "spend": "15702"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "25",
     "cpm": "18797.263682",
     "ctr": "3.109453",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "804",
     "spend": "15113"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "24",
     "cpm": "19309.677419",
     "ctr": "3.096774",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "19:00:00 - 19:59:59",
     "impressions": "775",
     "spend": "14965"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "21",
     "cpm": "24552.980132",
     "ctr": "3.476821",
     "date_start": "2022-04-15",
     "date_stop": "2022-04-15",
     "hourly_stats_aggregated_by_advertiser_time_zone": "23:00:00 - 23:59:59",
     "impressions": "604",
     "spend": "14830"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "24",
     "cpm": "19958.164642",
     "ctr": "3.238866",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "15:00:00 - 15:59:59",
     "impressions": "741",
     "spend": "14789"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "24",
     "cpm": "20158.686731",
     "ctr": "3.283174",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "20:00:00 - 20:59:59",
     "impressions": "731",
     "spend": "14736"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "23",
     "cpm": "15270.299145",
     "ctr": "2.457265",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "17:00:00 - 17:59:59",
     "impressions": "936",
     "spend": "14293"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "24",
     "cpm": "14477.596741",
     "ctr": "2.443992",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "17:00:00 - 17:59:59",
     "impressions": "982",
     "spend": "14217"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "22",
     "cpm": "20388.235294",
     "ctr": "3.235294",
     "date_start": "2022-04-13",
     "date_stop": "2022-04-13",
     "hourly_stats_aggregated_by_advertiser_time_zone": "12:00:00 - 12:59:59",
     "impressions": "680",
     "spend": "13864"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "21",
     "cpm": "14202.868852",
     "ctr": "2.151639",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "09:00:00 - 09:59:59",
     "impressions": "976",
     "spend": "13862"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "22",
     "cpm": "18067.973856",
     "ctr": "2.875817",
     "date_start": "2022-04-17",
     "date_stop": "2022-04-17",
     "hourly_stats_aggregated_by_advertiser_time_zone": "10:00:00 - 10:59:59",
     "impressions": "765",
     "spend": "13822"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "19",
     "cpm": "13556.112224",
     "ctr": "1.903808",
     "date_start": "2022-04-14",
     "date_stop": "2022-04-14",
     "hourly_stats_aggregated_by_advertiser_time_zone": "22:00:00 - 22:59:59",
     "impressions": "998",
     "spend": "13529"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",
     "campaign_name": "220401_\uc0c1\uc2dc\uc6b4\uc601(\uc2a4\ub9c8\ud2b8\uc2a4\ud1a0\uc5b4)",
     "clicks": "20",
     "cpm": "39163.74269",
     "ctr": "5.847953",
     "date_start": "2022-04-15",
     "date_stop": "2022-04-15",
     "hourly_stats_aggregated_by_advertiser_time_zone": "16:00:00 - 16:59:59",
     "impressions": "342",
     "spend": "13394"
 },
 <AdsInsights> {
     "account_name": "\ub370\uc2a4\ucee4_\ub514\ud050\ub808\uc774\ud130",
     "adset_id": "23849608671670122",
     "adset_name": "\uc778\uc2a4\ud0c0\uadf8\ub7a8_Seg1_CPC",
     "campaign_id": "23849608671640122",

In [122]:
df=pd.DataFrame(columns=fields2)
for field in fields2:
    df["{}".format(field)]=[x['{}'.format(field)] for x in insights4]

df

,account_name,campaign_name,campaign_id,adset_name,adset_id,hourly_stats_aggregated_by_advertiser_time_zone,impressions,clicks,cpm,spend,ctr
0,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg1_CPC,23849608671670122,23:00:00 - 23:59:59,1665,47,19270.870871,32086,2.822823
1,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg1_CPC,23849608671670122,23:00:00 - 23:59:59,1509,53,20546.056991,31004,3.51226
2,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg1_CPC,23849608671670122,18:00:00 - 18:59:59,1150,40,20492.173913,23566,3.478261
3,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg1_CPC,23849608671670122,20:00:00 - 20:59:59,1075,38,21740.465116,23371,3.534884
4,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg1_CPC,23849608671670122,21:00:00 - 21:59:59,884,38,25973.9819,22961,4.298643
...,...,...,...,...,...,...,...,...,...,...,...
471,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg2_신혼,23849609055930122,15:00:00 - 15:59:59,1,0,2000,2,0
472,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg2_신혼,23849609055930122,18:00:00 - 18:59:59,1,0,2000,2,0
473,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg2_신혼,23849609055930122,19:00:00 - 19:59:59,1,0,1000,1,0
474,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg2_신혼,23849609055930122,05:00:00 - 05:59:59,1,0,1000,1,0
475,데스커_디큐레이터,220401_상시운영(스마트스토어),23849608671640122,인스타그램_Seg2_신혼,23849609055930122,17:00:00 - 17:59:59,2,0,500,1,0

In [162]:
df['hourly_stats_aggregated_by_advertiser_time_zone']

0    23:00:00 - 23:59:59
1    21:00:00 - 21:59:59
Name: hourly_stats_aggregated_by_advertiser_time_zone, dtype: object